### ISSUE TITLE
Segmentation fault (core dumped) - Ubuntu Mate Linux

### ISSUE THREAD

**Issue by ToferC** [machinalis/iepy#97] opened 2016-05-26 01:38 UTC
Hello,

I'm trying to get iepy up and running on 64 bit 16.04 Ubuntu Mate Linux using the following packages in conda:

```
mkl=11.3.3=0
numpy=1.11.0=py34_1
openssl=1.0.2h=0
pip=8.1.1=py34_1
python=3.4.4=0
readline=6.2=2
setuptools=21.2.1=py34_0
sqlite=3.13.0=0
tk=8.5.18=0
wheel=0.29.0=py34_0
xz=5.0.5=1
zlib=1.2.8=3

```

But I'm getting the result: 'Segmentation fault (core dumped)'.  I've done some research and the most common cause is an error in C code that causes Linux to raise the fault, but I've got no information to help me debug. I'm hoping someone could point out a possible error with my packages or other cause.

Thanks in advance.

**Comment by jmansilla** [comment] 2016-06-02 20:30
We never used IEPY with conda, so not sure if that may be the cause (or related with) the issue

**Comment by jmansilla** [comment] 2016-08-16 21:56
Hi @ToferC 

Did you find anything worth trying regarding this issue?
If not, I'll be closing this request soon

**Comment by j0hn** [comment] 2016-09-02 18:21
I'll close this for a lack of response.

**Closed by j0hn** 2016-09-02 18:21 UTC
